language: python
python:
  - "2.7"
before_script:
  - mysql -e 'create database {{ cookiecutter.project_db }} character set utf8;'
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - DEBUG=False SECRET_KEY='FOO' ALLOWED_HOSTS=localhost, DATABASE_URL=mysql://root@localhost/{{ cookiecutter.project_db }}
script:
  flake8 {{ cookiecutter.project_name }} && coverage run manage.py test
after_success:
  coveralls
