sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
addons:
  postgresql: "9.3"
before_script:
  - createdb sugardough_db
install:
  - pip install tox cookiecutter
env:
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=tests
script:
  ./bin/test_sugardough.sh
